apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: proxy-tls
  namespace: default
spec:
  secretName: proxy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: proxy.coding4fun.org
  dnsNames:
  - proxy.coding4fun.org
  acme:
    config:
    - http01:
        ingress: helloweb
      domains:
      - proxy.coding4fun.org
